"""Reviewed exercise data for deterministic weekly plan generation."""


ALL_EXPERIENCE_LEVELS = (
    "Complete beginner",
    "Returning to exercise",
)
RETURNING_EXPERIENCE_LEVEL = ("Returning to exercise",)

CONSISTENCY_GOALS = (
    "Start exercising regularly",
    "Improve overall fitness",
)
STRENGTH_GOALS = CONSISTENCY_GOALS + ("Get stronger",)
CARDIO_GOALS = CONSISTENCY_GOALS + ("Increase stamina",)
MOBILITY_GOALS = CONSISTENCY_GOALS + (
    "Improve flexibility and mobility",
)

SOURCES = {
    "cdc-adult-activity": {
        "title": "CDC Adult Activity: An Overview",
        "url": (
            "https://www.cdc.gov/physical-activity-basics/guidelines/"
            "adults.html"
        ),
    },
    "nhs-strength-exercises": {
        "title": "NHS Strength exercises",
        "url": "https://www.nhs.uk/live-well/exercise/strength-exercises/",
    },
    "nhs-strength-flexibility": {
        "title": "NHS How to improve your strength and flexibility",
        "url": (
            "https://www.nhs.uk/live-well/exercise/"
            "how-to-improve-strength-flexibility/"
        ),
    },
    "ace-exercise-library": {
        "title": "ACE Exercise Library",
        "url": (
            "https://www.acefitness.org/resources/everyone/"
            "exercise-library/"
        ),
    },
}


EXERCISE_LIBRARY = (
    {
        "exercise_id": "walking",
        "name": "Walking",
        "activity_type": "cardio",
        "movement_pattern": "cardio",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": CARDIO_GOALS,
        "preference_tags": ("Walking",),
        "prescription_type": "minutes",
        "source_ids": ("cdc-adult-activity",),
    },
    {
        "exercise_id": "walk_jog_intervals",
        "name": "Walk-jog intervals",
        "activity_type": "cardio",
        "movement_pattern": "cardio",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": CARDIO_GOALS,
        "preference_tags": ("Jogging or running", "Walking"),
        "prescription_type": "minutes",
        "source_ids": ("cdc-adult-activity",),
    },
    {
        "exercise_id": "jogging",
        "name": "Jogging",
        "activity_type": "cardio",
        "movement_pattern": "cardio",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": RETURNING_EXPERIENCE_LEVEL,
        "goal_tags": CARDIO_GOALS,
        "preference_tags": ("Jogging or running",),
        "prescription_type": "minutes",
        "source_ids": ("cdc-adult-activity",),
    },
    {
        "exercise_id": "cycling",
        "name": "Cycling",
        "activity_type": "cardio",
        "movement_pattern": "cardio",
        "equipment_options": (
            "Bicycle or stationary bike",
            "Full gym access",
        ),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": CARDIO_GOALS,
        "preference_tags": ("Cycling",),
        "prescription_type": "minutes",
        "source_ids": ("cdc-adult-activity",),
    },
    {
        "exercise_id": "sit_to_stand",
        "name": "Sit-to-stand",
        "activity_type": "bodyweight",
        "movement_pattern": "squat",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("nhs-strength-exercises",),
    },
    {
        "exercise_id": "bodyweight_squat",
        "name": "Bodyweight squat",
        "activity_type": "bodyweight",
        "movement_pattern": "squat",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("nhs-strength-exercises",),
    },
    {
        "exercise_id": "wall_push_up",
        "name": "Wall push-up",
        "activity_type": "bodyweight",
        "movement_pattern": "upper_push",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("nhs-strength-exercises",),
    },
    {
        "exercise_id": "standing_calf_raise",
        "name": "Standing calf raise",
        "activity_type": "bodyweight",
        "movement_pattern": "lower_body",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("nhs-strength-exercises",),
    },
    {
        "exercise_id": "standing_side_leg_raise",
        "name": "Standing side leg raise",
        "activity_type": "bodyweight",
        "movement_pattern": "lower_body",
        "equipment_options": (),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("nhs-strength-exercises",),
    },
    {
        "exercise_id": "glute_bridge",
        "name": "Glute bridge",
        "activity_type": "bodyweight",
        "movement_pattern": "hinge",
        "equipment_options": (),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "opposite_arm_leg_reach",
        "name": "Opposite arm and leg reach (bird dog)",
        "activity_type": "bodyweight",
        "movement_pattern": "core",
        "equipment_options": (),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "dead_bug",
        "name": "Dead bug",
        "activity_type": "bodyweight",
        "movement_pattern": "core",
        "equipment_options": (),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Bodyweight workouts", "Strength training"),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "resistance_band_squat",
        "name": "Resistance-band squat",
        "activity_type": "strength",
        "movement_pattern": "squat",
        "equipment_options": ("Resistance bands", "Full gym access"),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "resistance_band_row",
        "name": "Resistance-band row",
        "activity_type": "strength",
        "movement_pattern": "upper_pull",
        "equipment_options": ("Resistance bands", "Full gym access"),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "resistance_band_chest_press",
        "name": "Resistance-band chest press",
        "activity_type": "strength",
        "movement_pattern": "upper_push",
        "equipment_options": ("Resistance bands", "Full gym access"),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "band_pull_apart",
        "name": "Band pull-apart",
        "activity_type": "strength",
        "movement_pattern": "upper_pull",
        "equipment_options": ("Resistance bands", "Full gym access"),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "goblet_squat",
        "name": "Goblet squat",
        "activity_type": "strength",
        "movement_pattern": "squat",
        "equipment_options": (
            "Dumbbells",
            "Kettlebell",
            "Full gym access",
        ),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "weighted_romanian_deadlift",
        "name": "Weighted Romanian deadlift",
        "activity_type": "strength",
        "movement_pattern": "hinge",
        "equipment_options": (
            "Dumbbells",
            "Kettlebell",
            "Full gym access",
        ),
        "optional_equipment": (),
        "experience_levels": RETURNING_EXPERIENCE_LEVEL,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "one_arm_weighted_row",
        "name": "One-arm weighted row",
        "activity_type": "strength",
        "movement_pattern": "upper_pull",
        "equipment_options": (
            "Dumbbells",
            "Kettlebell",
            "Full gym access",
        ),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "dumbbell_floor_press",
        "name": "Dumbbell floor press",
        "activity_type": "strength",
        "movement_pattern": "upper_push",
        "equipment_options": ("Dumbbells", "Full gym access"),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "dumbbell_shoulder_press",
        "name": "Dumbbell shoulder press",
        "activity_type": "strength",
        "movement_pattern": "upper_push",
        "equipment_options": ("Dumbbells", "Full gym access"),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "leg_press",
        "name": "Leg press",
        "activity_type": "strength",
        "movement_pattern": "squat",
        "equipment_options": ("Full gym access",),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "chest_press_machine",
        "name": "Chest press machine",
        "activity_type": "strength",
        "movement_pattern": "upper_push",
        "equipment_options": ("Full gym access",),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "lat_pulldown",
        "name": "Lat pulldown",
        "activity_type": "strength",
        "movement_pattern": "upper_pull",
        "equipment_options": ("Full gym access",),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "seated_cable_row",
        "name": "Seated cable row",
        "activity_type": "strength",
        "movement_pattern": "upper_pull",
        "equipment_options": ("Full gym access",),
        "optional_equipment": (),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": STRENGTH_GOALS,
        "preference_tags": ("Strength training",),
        "prescription_type": "sets_reps",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "cat_cow",
        "name": "Cat-cow",
        "activity_type": "mobility",
        "movement_pattern": "mobility",
        "equipment_options": (),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": MOBILITY_GOALS,
        "preference_tags": ("Yoga or mobility",),
        "prescription_type": "minutes",
        "source_ids": ("ace-exercise-library",),
    },
    {
        "exercise_id": "gentle_full_body_mobility",
        "name": "Gentle full-body mobility flow",
        "activity_type": "mobility",
        "movement_pattern": "mobility",
        "equipment_options": (),
        "optional_equipment": ("Exercise mat",),
        "experience_levels": ALL_EXPERIENCE_LEVELS,
        "goal_tags": MOBILITY_GOALS,
        "preference_tags": ("Yoga or mobility",),
        "prescription_type": "minutes",
        "source_ids": ("nhs-strength-flexibility",),
    },
)
